mqtt:
  enabled: False

ffmpeg:
  hwaccel_args: preset-vaapi

# Configuración de Streams en HD para la interfaz web (go2rtc)
go2rtc:
  streams:
    imou_cruiser_ptz:
      - rtsp://admin:L2xr1zum@192.168.100.124:554/cam/realmonitor?channel=1&subtype=0
    imou_cruiser_fija:
      - rtsp://admin:L2xr1zum@192.168.100.124:554/cam/realmonitor?channel=2&subtype=0

cameras:
  imou_cruiser_ptz:
    ffmpeg:
      input_args: preset-rtsp-generic
      inputs:
        # Usa go2rtc para la grabación HD
        - path: rtsp://127.0.0.1:8554/imou_cruiser_ptz
          roles:
            - record
        # Usa subtype=1 directamente para la detección
        - path: rtsp://admin:L2xr1zum@192.168.100.124:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5

    record:
      enabled: True
      retain:
        days: 7
        mode: all

    onvif:
      host: 192.168.100.124
      port: 80
      user: admin
      password: L2xr1zum

  imou_cruiser_fija:
    ffmpeg:
      input_args: preset-rtsp-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/imou_cruiser_fija
          roles:
            - record
        - path: rtsp://admin:L2xr1zum@192.168.100.124:554/cam/realmonitor?channel=2&subtype=1
          roles:
            - detect

    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5

    record:
      enabled: True
      retain:
        days: 7
        mode: all