mqtt:
  enabled: False

ffmpeg:
  hwaccel_args: preset-vaapi

# Módulo de streaming en tiempo real (pasa el flujo nativo 4K/3K directo al navegador)
go2rtc:
  streams:
    imou_cruiser_ptz:
      - "rtsp://admin:L2xr1zum@192.168.100.124:554/cam/realmonitor?channel=1&subtype=0#transport=tcp"
    imou_cruiser_fija:
      - "rtsp://admin:L2xr1zum@192.168.100.124:554/cam/realmonitor?channel=2&subtype=0#transport=tcp"

cameras:
  imou_cruiser_ptz:
    ffmpeg:
      inputs:
        # Usa el stream de go2rtc para la grabación en UHD
        - path: rtsp://127.0.0.1:8554/imou_cruiser_ptz
          roles:
            - record
        # Usa el stream secundario SD directo para que el detector no sature la CPU
        - path: rtsp://admin:L2xr1zum@192.168.100.124:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5

    record:
      enabled: True
      retain:
        days: 7
        mode: all

  imou_cruiser_fija:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/imou_cruiser_fija
          roles:
            - record
        - path: rtsp://admin:L2xr1zum@192.168.100.124:554/cam/realmonitor?channel=2&subtype=1
          roles:
            - detect

    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5

    record:
      enabled: True
      retain:
        days: 7
        mode: all